### ISSUE TITLE
Can't get CSRF

### ISSUE THREAD

**Issue by yogiwisesa** [yatsenkolesh/instagram-nodejs#31]
I used this code

`let Instagram = require('instagram-nodejs-without-api');

Instagram = new Instagram()

Instagram.getCsrfToken()
.then((csrf) =>
{
  Instagram.csrfToken = csrf;
  console.log(csrf)
}).then(() =>
{
  Instagram.auth('----', '-----').then(sessionId =>
  {

    Instagram.sessionId = sessionId

    Instagram.getUserDataByUsername('----').then((t) =>
    {
      Instagram.getUserFollowers(JSON.parse(t).graphql.user.id).then((t) =>
      {
        console.log(t); // - instagram followers for user "username-for-get"
      })
    })

  })
})`

it's always logged empty string ("").

**Comment by yatsenkolesh** [comment]
Hello. Please check this in 1.0.0 version.

**Comment by yatsenkolesh** [comment]
It's working ? Your issue is resolved ?

**Comment by yogiwisesa** [comment]
Isn't resolved yet. When I log the Instagram, It's returned undefined.

**Comment by yatsenkolesh** [comment]
what version of package do u use ?

**Comment by yogiwisesa** [comment]
"instagram-nodejs-without-api": "^1.0.0",

Or maybe I did something wrong?

**Comment by yatsenkolesh** [comment]
Yeah. This is problem and I will resolve it soon.

**Comment by yatsenkolesh** [comment]
We are fixed!  I updated the version. Try to use 1.0.3, but if u will have challenge required exception - push me.

**Comment by yogiwisesa** [comment]
Yeah, I got the CSRF but It's always said that the authentication was error and challange required. what is that?

**Comment by wixvii** [comment]
same issue.

**Comment by wixvii** [comment]
I can get token but can not get sessionId, it says "Instagram authentication failed (challenge required erro)"

**Comment by yatsenkolesh** [comment]
@yogiwisesa try to change account or auth from a web interface. Instagram is changing API and we should prepare functional for instagram challenges.

**Comment by yogiwisesa** [comment]
I already changed my password, but still isn't working.
